on:
  pull_request:
    branches:
      - master

concurrency:
  group: pytests
  cancel-in-progress: true

name: pytests
jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
          # Only return if PR is not in draft state
          filterOutDraft: 1

      - name: Check PR message
        id: check
        run: |
          message=$(echo "${{ steps.PR.outputs.pr_body }}")
          echo "Message is $message"
          if [[ "$message" == "" ]] ; then
            echo "Pull request message not provided!!"
            exit 1
          fi

  pytest:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:

      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager wheel
          pip install --upgrade --upgrade-strategy eager pytest
          pip install --upgrade --upgrade-strategy eager pytest-gitignore
          pip install --upgrade --upgrade-strategy eager pytest-github-actions-annotate-failures
          pip install --upgrade --upgrade-strategy eager .

      - name: Test with pytest
        run: |
          pytest -s -v
