on:
  pull_request:
    branches:
      - master
      - main

name: pytests
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:

      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install pytest
          # Required for pytests
          pip install pandas
          pip install pytest-gitignore
          pip install pytest-github-actions-annotate-failures
          pip install .

      - name: Test with pytest
        run: |
          pytest -s -v
