on:
  push:
    branches:
      - master
      - main

name: PyPI
jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'VERSION-SKIP-CI')"
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:

      - name: Set envvars
        run: |
          repo_name=$(echo ${{ github.repository }} | sed "s/${{ github.repository_owner }}\///g")
          echo "REPO_NAME=$repo_name" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          if [ "${GITHUB_REF#refs/heads/}" != "master" ] && [ "${GITHUB_REF#refs/heads/}" != "main" ] ; then
            echo "SUFFIX=$(echo -${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          fi

      - name: Check envvars
        run: |
          echo "branch: ${{ env.BRANCH_NAME }}"
          echo "repo: ${{ env.REPO_NAME }}"
          echo "suffix: ${{ env.SUFFIX }}"

      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: build
        run: |
          python -m pip install --upgrade pip
          python setup.py sdist

      - name: make doc
        if: ${{ env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'main' }}
        run: |
          pip install -r requirements.txt
          pip install pdoc3
          pdoc --html ${{ env.REPO_NAME }} -o docs
          mv docs/${{ env.REPO_NAME }}/* docs/
          rm -r docs/${{ env.REPO_NAME }}

      - name: commit doc
        if: ${{ env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'main' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs"

      - name: Push doc
        if: ${{ env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'main' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ORG_TOKEN_CICD }}
          branch: "gh-pages"
          force: true

      - name: topypi
        if: ${{ env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'main' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.ORG_PYPI_LOGIN }}
          password: ${{ secrets.ORG_PYPI_PASSWD }}
          skip_existing: true
          verbose: true
